# configuration:
#  - Debug
#  - Release

environment:
  matrix:
  - arch: x64
    vsver: 120
  - arch: x64
    vsver: 140
  - arch: x64
    vsver: 90

install:
- ps: install-module pscx -scope CurrentUser

build: off

build_script:
- ps: >-
    .\build.ps1 -arch:$env:arch -vsver:$env:vsver -debug
